emoji = true

[[commit_types]]
name = "feat"
emoji = "âœ¨"
description = "a new feature"

[[commit_types]]
name = "fix"
emoji = "ğŸ›"
description = "a bug fix"

[[commit_types]]
name = "docs"
emoji = "ğŸ“š"
description = "documentation changes"

[[commit_types]]
name = "refactor"
emoji = "ğŸ”¨"
description = "a non style change that improves the project"

[[commit_types]]
name = "dev"
emoji = "ğŸ’»"
description = "improves the dev / project experience"

[[commit_types]]
name = "perf"
emoji = "âš¡"
description = "improves performance"

[[commit_types]]
name = "test"
emoji = "ğŸš¨"
description = "manages tests"

[[commit_types]]
name = "build"
emoji = "ğŸ“¦"
description = "manages build system or external dependencies"

[[commit_types]]
name = "ci"
emoji = "ğŸ¤–"
description = "manages ci"

[[commit_types]]
name = "revert"
emoji = "âª"
description = "reverts a previous commit"

[[commit_types]]
name = "chore"
emoji = "ğŸ§¹"
description = "(if using often, we should add a new commit type) not included in other commit types"
