emoji = true

[[commit_types]]
name = "feat"
emoji = "âœ¨"
description = "a new feature"

[[commit_types]]
name = "fix"
emoji = "ğŸ›"
description = "a bug fix"

[[commit_types]]
name = "docs"
emoji = "ğŸ“š"
description = "documentation changes"

[[commit_types]]
name = "style"
emoji = "ğŸ’„"
description = "changes that do not affect the meaning of the code"

[[commit_types]]
name = "refactor"
emoji = "ğŸ”¨"
description = "a code change that neither fixes a bug nor adds a feature"

[[commit_types]]
name = "perf"
emoji = "âš¡"
description = "a code change that improves performance"

[[commit_types]]
name = "test"
emoji = "ğŸš¨"
description = "adding missing tests or correcting existing tests"

[[commit_types]]
name = "build"
emoji = "ğŸ“¦"
description = "changes that affect the build system or external dependencies"

[[commit_types]]
name = "ci"
emoji = "ğŸ¤–"
description = "managing ci"

[[commit_types]]
name = "revert"
emoji = "âª"
description = "reverts a previous commit"

[[commit_types]]
name = "dev"
emoji = "ğŸ’»"
description = "modifies the dev / project experience"

[[commit_types]]
name = "chore"
emoji = "ğŸ§¹"
description = "(if using often, we should add a new commit type) not included in other commit types"

